# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from proto import inference_pb2 as proto_dot_inference__pb2

GRPC_GENERATED_VERSION = "1.80.0"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + " but the generated code in proto/inference_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class InferenceServiceStub(object):
    """─────────────────────────────────────────────
    Service Definitions
    ─────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
            "/inference.InferenceService/Predict",
            request_serializer=proto_dot_inference__pb2.InferenceRequest.SerializeToString,
            response_deserializer=proto_dot_inference__pb2.InferenceResponse.FromString,
            _registered_method=True,
        )
        self.BatchPredict = channel.unary_unary(
            "/inference.InferenceService/BatchPredict",
            request_serializer=proto_dot_inference__pb2.BatchInferenceRequest.SerializeToString,
            response_deserializer=proto_dot_inference__pb2.BatchInferenceResponse.FromString,
            _registered_method=True,
        )
        self.StreamPredict = channel.stream_stream(
            "/inference.InferenceService/StreamPredict",
            request_serializer=proto_dot_inference__pb2.Transaction.SerializeToString,
            response_deserializer=proto_dot_inference__pb2.InferenceResponse.FromString,
            _registered_method=True,
        )
        self.GetFeatures = channel.unary_unary(
            "/inference.InferenceService/GetFeatures",
            request_serializer=proto_dot_inference__pb2.FeatureRequest.SerializeToString,
            response_deserializer=proto_dot_inference__pb2.FeatureVector.FromString,
            _registered_method=True,
        )
        self.Health = channel.unary_unary(
            "/inference.InferenceService/Health",
            request_serializer=proto_dot_inference__pb2.HealthRequest.SerializeToString,
            response_deserializer=proto_dot_inference__pb2.HealthResponse.FromString,
            _registered_method=True,
        )


class InferenceServiceServicer(object):
    """─────────────────────────────────────────────
    Service Definitions
    ─────────────────────────────────────────────

    """

    def Predict(self, request, context):
        """Single transaction scoring"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BatchPredict(self, request, context):
        """Batch scoring — lower overhead per request"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StreamPredict(self, request_iterator, context):
        """Streaming: send transactions, receive real-time scores"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetFeatures(self, request, context):
        """Direct feature vector retrieval"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Health(self, request, context):
        """Health / readiness probe"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Predict": grpc.unary_unary_rpc_method_handler(
            servicer.Predict,
            request_deserializer=proto_dot_inference__pb2.InferenceRequest.FromString,
            response_serializer=proto_dot_inference__pb2.InferenceResponse.SerializeToString,
        ),
        "BatchPredict": grpc.unary_unary_rpc_method_handler(
            servicer.BatchPredict,
            request_deserializer=proto_dot_inference__pb2.BatchInferenceRequest.FromString,
            response_serializer=proto_dot_inference__pb2.BatchInferenceResponse.SerializeToString,
        ),
        "StreamPredict": grpc.stream_stream_rpc_method_handler(
            servicer.StreamPredict,
            request_deserializer=proto_dot_inference__pb2.Transaction.FromString,
            response_serializer=proto_dot_inference__pb2.InferenceResponse.SerializeToString,
        ),
        "GetFeatures": grpc.unary_unary_rpc_method_handler(
            servicer.GetFeatures,
            request_deserializer=proto_dot_inference__pb2.FeatureRequest.FromString,
            response_serializer=proto_dot_inference__pb2.FeatureVector.SerializeToString,
        ),
        "Health": grpc.unary_unary_rpc_method_handler(
            servicer.Health,
            request_deserializer=proto_dot_inference__pb2.HealthRequest.FromString,
            response_serializer=proto_dot_inference__pb2.HealthResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "inference.InferenceService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers("inference.InferenceService", rpc_method_handlers)


# This class is part of an EXPERIMENTAL API.
class InferenceService(object):
    """─────────────────────────────────────────────
    Service Definitions
    ─────────────────────────────────────────────

    """

    @staticmethod
    def Predict(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/inference.InferenceService/Predict",
            proto_dot_inference__pb2.InferenceRequest.SerializeToString,
            proto_dot_inference__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def BatchPredict(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/inference.InferenceService/BatchPredict",
            proto_dot_inference__pb2.BatchInferenceRequest.SerializeToString,
            proto_dot_inference__pb2.BatchInferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StreamPredict(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            "/inference.InferenceService/StreamPredict",
            proto_dot_inference__pb2.Transaction.SerializeToString,
            proto_dot_inference__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def GetFeatures(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/inference.InferenceService/GetFeatures",
            proto_dot_inference__pb2.FeatureRequest.SerializeToString,
            proto_dot_inference__pb2.FeatureVector.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Health(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/inference.InferenceService/Health",
            proto_dot_inference__pb2.HealthRequest.SerializeToString,
            proto_dot_inference__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
